
// 登录
const login = {
    REQUEST_USER_LOGIN : Symbol('REQUEST_USER_LOGIN'),
    REQUEST_USER_LOGIN_SUCCESS : Symbol('REQUEST_USER_LOGIN_SUCCESS'),
    REQUEST_USER_LOGIN_FAILED : Symbol('REQUEST_USER_LOGIN_FAILED'),
    REQUEST_GET_CAPTCHA : Symbol('REQUEST_GET_CAPTCHA'),
    USER_LOGIN_SHOW_CAPTCHA : Symbol('USER_LOGIN_SHOW_CAPTCHA'),
    USER_LOGIN_EXIT : Symbol('USER_LOGIN_EXIT')
};

// 找回密码
const findPassword = {
    CHECK_MOBILE_AVAILABLE : Symbol('CHECK_MOBILE_AVAILABLE'),
    MOBILE_AVAILABLE : Symbol('MOBILE_AVAILABLE'),
    MOBILE_UNAVAILABLE : Symbol('MOBILE_UNAVAILABLE'),
    FETCH_MOBILE_VERIFICATION_CODE : Symbol('FETCH_MOBILE_VERIFICATION_CODE'),
    FETCH_MOBILE_VERIFICATION_CODE_SUCCESS : Symbol('FETCH_MOBILE_VERIFICATION_CODE_SUCCESS'),
    FETCH_MOBILE_VERIFICATION_CODE_FAILED : Symbol('FETCH_MOBILE_VERIFICATION_CODE_FAILED'),
    FIND_PWD_FIRST_STEP_SHOW_CAPTCHA : Symbol('FIND_PWD_FIRST_STEP_SHOW_CAPTCHA')
};

export {login, findPassword}
